### ISSUE TITLE
Possibly bad path grammar

### ISSUE THREAD

**Issue by ocket8888** [mozilla/sphinx-js#103]
Python v3.6.7
Sphinx v1.8.5
sphinx_js v2.7.1
typedoc v0.14.2 (using Typescript v3.2.4)

I ran into an error where parsimonious threw an exception trying to deal with some path (stack trace just named it as `../../../docs/app/ap`) but by adding my own print statement in doclets.py I was able to find out it seemed to be having trouble with parsing files with `.` in the name. Here's the output with that path print included:

```
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.8.5
WARNING: The config value `js_source_path' has type `list', defaults to `str'.
loading pickled environment... failed: No such config value: js_language

Using TypeScript 3.2.4 from /usr/lib/node_modules/typedoc/node_modules/typescript/lib

JSON written to /tmp/tmpttvvhqwa

parsing path: ../../../docs/app/app.component.external:app/app.component

Exception occurred:
  File "/usr/local/lib/python3.6/dist-packages/parsimonious/expressions.py", line 127, in match
    raise error
parsimonious.exceptions.ParseError: Rule 'path' didn't match at '../../../docs/app/ap' (line 1, column 1).
The full traceback has been saved in /tmp/sphinx-err-v8cgfoxe.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:71: recipe for target 'html' failed
make: *** [html] Error 2
```

... and here's the "full traceback" it talks about:
```
# Sphinx version: 1.8.5
# Python version: 3.6.7 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/usr/local/lib/python3.6/dist-packages/sphinx/application.py", line 325, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python3.6/dist-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python3.6/dist-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python3.6/dist-packages/sphinx_js/doclets.py", line 44, in gather_doclets
    doclet_full_path(d, root_for_relative_paths),
  File "/usr/local/lib/python3.6/dist-packages/sphinx_js/doclets.py", line 190, in doclet_full_path
    path_and_formal_params['path'].parse(path))
  File "/usr/local/lib/python3.6/dist-packages/parsimonious/expressions.py", line 110, in parse
    node = self.match(text, pos=pos)
  File "/usr/local/lib/python3.6/dist-packages/parsimonious/expressions.py", line 127, in match
    raise error
parsimonious.exceptions.ParseError: Rule 'path' didn't match at '../../../docs/app/ap' (line 1, column 1).
```

**Comment by skddc** [comment]
Also see #143
