### ISSUE TITLE
Rule 'path_and_formal_params' didn't match at

### ISSUE THREAD

**Issue by joshglenn** [mozilla/sphinx-js#109]
I am using sphinx-js for the first time. When using this directive:

```
.. js:autoclass:: MyClass
  :members:
```

I get successful output from my test class called MyClass.

However, several of my modules have identical names. So I wanted to test the autoclass directive telling the filename directly, like this:

```
.. js:autoclass:: ../mson-react/MyClass.js.MyClass
  :members:
```

I get an error message:

```
Exception occurred:
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/parsimonious/expressions.py", line 127, in match
    raise error
parsimonious.exceptions.ParseError: Rule 'path_and_formal_params' didn't match at '../mson-react/MyClas' (line 1, column 1).
```

Any idea how I can diagnose this?

**Comment by joshglenn** [comment]
Here is the traceback:

```
# Sphinx version: 1.8.5
# Python version: 3.7.1 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 14%] rst_cheatsheet
#   
#   reading sources... [ 28%] mson-react
#   
#   reading sources... [ 42%] mson
#   
#   reading sources... [ 57%] custom-components
#   
#   reading sources... [ 71%] index
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.5) from /Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from /Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/alabaster/__init__.py
#   sphinx_js (unknown version) from /Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx_js/__init__.py
Traceback (most recent call last):
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2328, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2358, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2631, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx/domains/__init__.py", line 239, in run
    return BaseDirective.run(self)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx_js/directives.py", line 60, in run
    return AutoClassRenderer.from_directive(self, app).rst_nodes()
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx_js/renderers.py", line 58, in from_directive
    options=directive.options)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/sphinx_js/renderers.py", line 38, in __init__
    self._partial_path, self._explicit_formal_params = PathVisitor().parse(arguments[0])
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/parsimonious/nodes.py", line 247, in parse
    return self._parse_or_match(text, pos, 'parse')
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/parsimonious/nodes.py", line 282, in _parse_or_match
    return self.visit(getattr(self.grammar, method_name)(text, pos=pos))
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/parsimonious/grammar.py", line 123, in parse
    return self.default_rule.parse(text, pos=pos)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/parsimonious/expressions.py", line 110, in parse
    node = self.match(text, pos=pos)
  File "/Users/josh/.virtualenvs/mson-docs/lib/python3.7/site-packages/parsimonious/expressions.py", line 127, in match
    raise error
parsimonious.exceptions.ParseError: Rule 'path_and_formal_params' didn't match at '../mson-react/MyClas' (line 1, column 1).
```

**Comment by joshglenn** [comment]
So, I ran across #94 . I made the change described [in this pull request](https://github.com/mozilla/sphinx-js/pull/95/commits/3c6b71beeb46c087776d08d74f82118a93d519f4)

Now, the function I am attempting works, but the formatted html shows the path and module name instead of the class name. Take a look at the attached photos.

Working properly...

<img width="668" alt="Screen Shot 2019-07-04 at 3 27 45 PM" src="https://user-images.githubusercontent.com/6953274/60686884-dcd54180-9e70-11e9-9c6d-487f9f57fdbc.png">


Not working properly... 

<img width="701" alt="Screen Shot 2019-07-04 at 3 27 52 PM" src="https://user-images.githubusercontent.com/6953274/60686886-de066e80-9e70-11e9-910a-00e0f87f06fe.png">

or, at least, not the result I was hoping for / expecting.

Could someone shed some light on this, please?

**Comment by erikrose** [comment]
@joshglenn Could you share the code you're running sphinx-js over, or (even better) a reduced subset that still throws the error? #94 is slow getting into my review queue because it lacks a test case.
