### ISSUE TITLE
ParseError: Rule 'name' didn't match at '/'

### ISSUE THREAD

**Issue by dobesv** [mozilla/sphinx-js#134]
Getting this obtuse stack trace when building my docs:

```
# Sphinx version: 1.8.5
# Python version: 2.7.17 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 325, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python2.7/dist-packages/sphinx_js/doclets.py", line 45, in gather_doclets
    doclet_full_path(d, root_for_relative_paths),
  File "/usr/local/lib/python2.7/dist-packages/sphinx_js/doclets.py", line 214, in doclet_full_path
    path_and_formal_params['path'].parse(path))
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 110, in parse
    node = self.match(text, pos=pos)
  File "/usr/local/lib/python2.7/dist-packages/parsimonious/expressions.py", line 127, in match
    raise error
ParseError: Rule 'name' didn't match at '/' (line 1, column 74).
```

To reproduce, check out the code from `https://github.com/dobesv/planout-ts` and go to `docs` and run `make html`.

Strangely, I swear I was able to build these docs a few weeks ago and I haven't really changed much.  Maybe an issue with the new version of TypeScript ?

**Comment by reuben** [comment]
Looks like you have since then moved away from sphinx-js. Specific commit to reproduce is: https://github.com/dobesv/planout-ts/tree/1354eef2c41361eed9db8e9c3cd2ef9ed69c88fc

**Comment by dobesv** [comment]
@reuben Yeah, I gave up on it.
