### ISSUE TITLE
KeyError: 'id' processing TypeDoc

### ISSUE THREAD

**Issue by tavianator** [mozilla/sphinx-js#154]
Just tried out sphinx-js 3.1 on https://github.com/microsoft/bistring.  I'm getting the following error:

```
Handler <function analyze at 0x7f6538653550> for event 'builder-inited' threw an exception (exception: 'id')
```

I patched sphinx up a bit to get this trace:

```
Traceback (most recent call last):
  File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.8/site-packages/sphinx/events.py", line 110, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.8/site-packages/sphinx_js/__init__.py", line 60, in analyze
    app._sphinxjs_analyzer = analyzer.from_disk(abs_source_paths,
  File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.8/site-packages/sphinx_js/typedoc.py", line 40, in from_disk
    return cls(json, base_dir)
  File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.8/site-packages/sphinx_js/typedoc.py", line 29, in __init__
    ir_objects = self._convert_all_nodes(json)
  File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.8/site-packages/sphinx_js/typedoc.py", line 113, in _convert_all_nodes
    converted, more_todo = self._convert_node(todo.pop())
  File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.8/site-packages/sphinx_js/typedoc.py", line 160, in _convert_node
    interfaces=self._related_types(node, kind='implementedTypes'),
  File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.8/site-packages/sphinx_js/typedoc.py", line 227, in _related_types
    pathname = Pathname(make_path_segments(self._index[type['id']],
KeyError: 'id'
```

Which points [here](https://github.com/mozilla/sphinx-js/blob/8991bd2a0f8fc72d22b521fb9401e9625da717a1/sphinx_js/typedoc.py#L225).

The variable `type` looks like this:

```python
{'type': 'reference', 'typeArguments': [{'type': 'reference', 'name': 'String'}], 'name': 'Iterable'}
```

So I expect the relevant code is [this line](https://github.com/microsoft/bistring/blob/7d620958e63030f01df6bb735bdd74eb42ad9412/js/src/bistring.ts#L17).

**Comment by erikrose** [comment]
Just off the top of my head, I wonder if we're hitting one of the cases I lopped off index_by_id() in 3d2415189edd7350b6e5cf50de590ac75f973f76. I took them off because they either didn't make sense or I couldn't get the branches to be taken in all the TS code I had to hand.

**Comment by erikrose** [comment]
If one of us can get it reduced, we can doubtless find a fix.

**Comment by tavianator** [comment]
Looks like this is enough to reproduce it:

```diff
diff --git a/tests/test_build_ts/source/class.ts b/tests/test_build_ts/source/class.ts
index f700886..b5fe2cc 100644
--- a/tests/test_build_ts/source/class.ts
+++ b/tests/test_build_ts/source/class.ts
@@ -53,3 +53,9 @@ interface OptionalThings {
   foop?(): void;
   boop?: boolean;
 }
+
+class Foo implements Iterable<string> {
+    [Symbol.iterator](): IterableIterator<string> {
+        return ""[Symbol.iterator]();
+    }
+}
```

Likewise I don't think I'llt have time to try to find a fix soon.

**Comment by erikrose** [comment]
Got a couple failing test cases written. The root of the problem is that there's no good way to represent intrinsics—in your case, interfaces made solely out of intrinsics—in the IR, because the field for `Class.interfaces` is a Pathname. I'll have to change that.

**Comment by erikrose** [comment]
More correctly, there's no way to represent types that cannot be expressed solely by a Pathname, like types that are built in or types that are parametrized (by `<>` or `key of` or whatever).

**Comment by ceelian** [comment]
Got the same error, is there a workaround to it in the meantime?

**Comment by erikrose** [comment]
If TS will let you break your type off and give it a name, like `someType = Iterable<string>` and then reference it where you need it like `class Foo implements someType`, you might be able to dodge the error.

**Comment by ceelian** [comment]
@erikrose thank you for the suggested workaround. How can I find where in the TS project the issue occurs? Because typedoc alone runs without errors.

**Comment by erikrose** [comment]
The problem is, as I explained in more depth above, a choice I made in our `ir.py` file. We'll need to fix it there. (Patches welcome; I don't know when I'll get to it.)

**Comment by bruce-wayne99** [comment]
Hello @erikrose just wanted to know if this issue is currently looked into. I am facing the same error as well.
