### ISSUE TITLE
make html returns error

### ISSUE THREAD

**Issue by davesargrad** [mozilla/sphinx-js#192]
I am trying to use sphinx-js. I've installed it with conda.
```
conda install -c conda-forge sphinx
conda install -c conda-forge sphinx-js
```

I've also installed jsdoc using 
`npm install jsdoc -g`

I run inside an empty "docs" subfolder of my project.
```
sphinx-quickstart
sphinx-apidoc -o . ..
```

The parent directory has valid "js" files.

I see the following error on "make html":
```
(docs) [dsargrad@sdbie-sargrad docs]$ make html
Running Sphinx v4.5.0
/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/mkdirp/lib/opts-arg.js:7
    opts = { mode: 0o777, fs, ...opts }
                              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at Object.load (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:105:18)
    at Requizzle.requizzle (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/requizzle.js:87:31)
    at infectProxy (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:79:31)
    at Module.targetModule.require.filepath [as require] (/home/dsargrad/.conda/envs/docs/lib/node_modules/jsdoc/node_modules/requizzle/lib/loader.js:97:44)
    at require (internal/module.js:20:19)

Sphinx error:
jsdoc found no JS files in the directories ['/home/dsargrad/dev/ves']. Make sure js_source_path is set correctly in conf.py. It is also possible (though unlikely) that jsdoc emitted invalid JSON.
make: *** [html] Error 2

```
![image](https://user-images.githubusercontent.com/48793689/163993636-6666dc81-2f5d-4aea-af5d-dc1424effbb6.png)

![image](https://user-images.githubusercontent.com/48793689/163993748-f4d7b3d1-899e-44a6-af35-b858a816b8a4.png)

I'm using sphinx 4.5.0, and sphinx-js 3.1.2
![image](https://user-images.githubusercontent.com/48793689/163994007-09e665a2-b906-4f69-b4b6-1f64c06b1efd.png)

![image](https://user-images.githubusercontent.com/48793689/164000678-d58548eb-0836-4cef-837f-40909aef1778.png)

![image](https://user-images.githubusercontent.com/48793689/163994480-cd42944e-9b10-48f5-aa61-631f166859e2.png)

I am using jsdoc 3.6.10
![image](https://user-images.githubusercontent.com/48793689/164000418-6107cfb5-fd13-4243-8fe0-7f04c5fbb5ff.png)

**Comment by davesargrad** [comment]
I closed this issue. The problem was in the way that I installed jsdoc.
