### ISSUE TITLE
json.loads crashes in analyze_jsdoc

### ISSUE THREAD

**Issue by tkhyn** [mozilla/sphinx-js#84]
Hi, since v2.7.1 and in relation to #67 and https://github.com/erikrose/sphinx-js/commit/688b2a855b2a896a47cb9dd3a56d055bd16fdb2e, I get the following error. I'm on linux (mint 18.3) with python 3.5.

```
# Sphinx version: 1.8.2
# Python version: 3.5.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/thomas/.buildout/eggs/Sphinx-1.8.2-py3.5.egg/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/thomas/.buildout/eggs/Sphinx-1.8.2-py3.5.egg/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/home/thomas/.buildout/eggs/Sphinx-1.8.2-py3.5.egg/sphinx/application.py", line 325, in _init_builder
    self.emit('builder-inited')
  File "/home/thomas/.buildout/eggs/Sphinx-1.8.2-py3.5.egg/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/home/thomas/.buildout/eggs/Sphinx-1.8.2-py3.5.egg/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/home/thomas/.buildout/eggs/sphinx_js-2.7.1-py3.5.egg/sphinx_js/doclets.py", line 29, in gather_doclets
    doclets = analyze(abs_source_paths, app)
  File "/home/thomas/.buildout/eggs/sphinx_js-2.7.1-py3.5.egg/sphinx_js/doclets.py", line 107, in analyze_jsdoc
    return load(temp)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Not sure what the best way to handle this could be. Try and detect the locale, maybe?

**Comment by enkimute** [comment]
Had the same issue on python 3.5.3

```bash
# Sphinx version: 1.8.5
# Python version: 3.5.3 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 325, in _init_builder
    self.emit('builder-inited')
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/usr/local/lib/python3.5/dist-packages/sphinx_js/doclets.py", line 29, in gather_doclets
    doclets = analyze(abs_source_paths, app)
  File "/usr/local/lib/python3.5/dist-packages/sphinx_js/doclets.py", line 107, in analyze_jsdoc
    return load(temp)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
upgrade to python 3.7.4 fixed that issue.

Next my project contained .mjs files only, and I had to patch in various places to get that to work.

Then jsDoc for some reason produced a list of duplicate fragments even for simple tests, and I ended up modifying sphynx-js to filter out double fragments (instead of just throw an error).

In the end, I still had to abandon the effort as jsDoc was to far of the mark interpreting my actual code. (substantial code modifications were needed to get to a usable output - and many doctags, that work fine in other tools (e.g. documentation.js) were not producing expected results - e.g. an extra ``@property {string} someprop`` in the docTag of a class would be ignored)

**Comment by Informatic** [comment]
`json.load` supports binary files from Python 3.6 on. `getwriter` defaults to passing all accessed attributes to unwrapped object (`TemporaryFile` in that case), which is `.read()` of a binary file. I guess this could be fixed by either rewrapping TemporaryFile fd in `getwriter`, or just directly opening that TemporaryFile in text-mode with `encoding="utf-8"`, wouldn't it?
