### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by frodo821** [mozilla/sphinx-js#90]
When I'm using sphinx-js and typedoc, an error was encountered.
Full stacktrace is below:

```
# Sphinx version: 1.8.3
# Python version: 3.6.5 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\sphinx\cmd\build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "c:\python36\lib\site-packages\sphinx\application.py", line 263, in __init__
    self._init_builder()
  File "c:\python36\lib\site-packages\sphinx\application.py", line 325, in _init_builder
    self.emit('builder-inited')
  File "c:\python36\lib\site-packages\sphinx\application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "c:\python36\lib\site-packages\sphinx\events.py", line 80, in emit
    results.append(callback(*args))
  File "c:\python36\lib\site-packages\sphinx_js\doclets.py", line 29, in gather_doclets
    doclets = analyze(abs_source_paths, app)
  File "c:\python36\lib\site-packages\sphinx_js\doclets.py", line 127, in analyze_typescript
    return parse_typedoc(temp)
  File "c:\python36\lib\site-packages\sphinx_js\typedoc.py", line 344, in parse_typedoc
    typedoc = TypeDoc(json.load(inputfile))
  File "c:\python36\lib\site-packages\sphinx_js\typedoc.py", line 55, in __init__
    self.convert_node(root)
  File "c:\python36\lib\site-packages\sphinx_js\typedoc.py", line 324, in convert_node
    self.convert_node(child)
  File "c:\python36\lib\site-packages\sphinx_js\typedoc.py", line 324, in convert_node
    self.convert_node(child)
  File "c:\python36\lib\site-packages\sphinx_js\typedoc.py", line 324, in convert_node
    self.convert_node(child)
  File "c:\python36\lib\site-packages\sphinx_js\typedoc.py", line 291, in convert_node
    type = self.make_type(node['getSignature']['type'])
TypeError: list indices must be integers or slices, not str
```

I tried to dump the node dictionary as shown below:

```python
{  
  'id':22,
  'name':'app_element',
  'kind':262144,
  'kindString':'Accessor',
  'flags':{  
    'isPublic':True,
    'isExported':True
  },
  'comment':{  
    'shortText':'The root element of your application.'
  },
  'getSignature':[  
    {  
      'id':23,
      'name':'__get',
      'kind':524288,
      'kindString':'Get signature',
      'flags':{  

      },
      'comment':{  
        'shortText':'The root element of your application.'
      },
      'type':{  
        'type':'union',
        'types':[  
          {  
            'type':'reference',
            'name':'Element'
          },
          {  
            'type':'intrinsic',
            'name':'null'
          }
        ]
      }
    }
  ],
  'setSignature':[  
    {  
      'id':24,
      'name':'__set',
      'kind':1048576,
      'kindString':'Set signature',
      'flags':{  

      },
      'comment':{  
        'shortText':'The root element of your application.'
      },
      'parameters':[  
        {  
          'id':25,
          'name':'v',
          'kind':32768,
          'kindString':'Parameter',
          'flags':{  

          },
          'type':{  
            'type':'union',
            'types':[  
              {  
                'type':'reference',
                'name':'Element'
              },
              {  
                'type':'intrinsic',
                'name':'null'
              }
            ]
          }
        }
      ],
      'type':{  
        'type':'intrinsic',
        'name':'void'
      }
    }
  ],
  'sources':[  
    {  
      'fileName':'core.ts',
      'line':42,
      'character':26
    },
    {  
      'fileName':'core.ts',
      'line':46,
      'character':26
    }
  ],
  '__parentId':15
}
```

**Comment by graup** [comment]
I just ran into the same problem. It seems the typedoc output has changed. It works with `npm install -g typedoc@0.13.0` but fails in `typedoc@0.14.0`.

Edit: Here's the change that causes this: https://github.com/TypeStrong/typedoc/pull/721

**Comment by codejamninja** [comment]
I am still getting this error

**Comment by graup** [comment]
@codejamninja I believe this fix has not been released yet. You can use the master of sphinx-js. Alternatively, downgrade your tsdoc version to `typedoc@0.13.0`.

**Comment by codejamninja** [comment]
Ok, thanks. Any idea when it will be released?
